export const btcList = [
  {
    id: 1,
    name: "ADA",
    desc: "Cardano",
    links: "https://coinmarketcap.com/currencies/cardano/",
  },
  {
    id: 2,
    name: "ADB",
    desc: "adbank",
    links: "https://coinmarketcap.com/currencies/adbank/",
  },
  {
    id: 3,
    name: "ATOM",
    desc: "Cosmos",
    links: "https://coinmarketcap.com/currencies/cosmos/",
  },
  {
    id: 4,
    name: "ATS",
    desc: "Atlas DEX",
    links: "https://crypto.com/price/atlas-dex",
  },
  {
    id: 5,
    name: "BCD",
    desc: "Bitcoin Diamond",
    links: "https://coinmarketcap.com/currencies/bitcoin-diamond/",
  },
  {
    id: 6,
    name: "BERRY",
    desc: "Rentberry",
    links: "https://coinmarketcap.com/currencies/rentberry/",
  },
  {
    id: 7,
    name: "BNB",
    desc: "Binance Coin",
    links: "https://coinmarketcap.com/currencies/bnb/",
  },
  {
    id: 8,
    name: "BSC",
    desc: "BowsCoin",
    links: "https://coinmarketcap.com/currencies/bowscoin/",
  },
  {
    id: 9,
    name: "BTC",
    desc: "Bitcoin",
    links: "https://coinmarketcap.com/currencies/bitcoin/",
  },
  {
    id: 10,
    name: "BTG",
    desc: "Bitcoin Gold",
    links: "https://coinmarketcap.com/currencies/bitcoin-gold/",
  },
  {
    id: 11,
    name: "BTT",
    desc: "BitTorrent",
    links: "https://coinmarketcap.com/currencies/bittorrent-new/",
  },
  {
    id: 12,
    name: "CRO",
    desc: "Crypto.com Coin",
    links: "https://coinmarketcap.com/currencies/crypto-com-coin/",
  },
  {
    id: 13,
    name: "CTR",
    desc: "Creator Platform",
    links: "https://coinmarketcap.com/currencies/creator-platform/",
  },
  {
    id: 14,
    name: "CTX",
    desc: "Cryptex Finance",
    links: "https://coinmarketcap.com/currencies/cryptex-finance/",
  },
  {
    id: 15,
    name: "CVC",
    desc: "Civic",
    links: "https://coinmarketcap.com/currencies/civic/",
  },
  {
    id: 16,
    name: "DADI",
    desc: "Edge",
    links: "https://crypto.com/price/edge",
  },
  {
    id: 17,
    name: "DNT",
    desc: "district0x",
    links: "https://coinmarketcap.com/currencies/district0x/",
  },
  {
    id: 18,
    name: "DOGE",
    desc: "Dogecoin",
    links: "https://coinmarketcap.com/currencies/dogecoin/",
  },
  {
    id: 19,
    name: "EBTC",
    desc: "Enhanced BTC",
    links: "https://coinmarketcap.com/currencies/ebtcnew/",
  },
  {
    id: 20,
    name: "ETH",
    desc: "Ethereum",
    links: "https://coinmarketcap.com/currencies/ethereum/",
  },
  {
    id: 21,
    name: "EXRN",
    desc: "EXRNchain",
    links: "https://coinmarketcap.com/currencies/exrnchain/",
  },
  {
    id: 22,
    name: "FOTA",
    desc: "Fortuna",
    links: "https://coinmarketcap.com/currencies/fota/",
  },
  {
    id: 23,
    name: "HYDRO",
    desc: "Hydro",
    links: "https://coinmarketcap.com/currencies/hydro/",
  },
  {
    id: 24,
    name: "KIN",
    desc: "Kin",
    links: "https://coinmarketcap.com/currencies/kin/",
  },
  {
    id: 25,
    name: "LEDU",
    desc: "Education Ecosystem",
    links: "https://coinmarketcap.com/currencies/education-ecosystem/",
  },
  {
    id: 26,
    name: "LPT",
    desc: "Livepeer",
    links: "https://coinmarketcap.com/currencies/livepeer/",
  },
  {
    id: 27,
    name: "LTC",
    desc: "Litecoin",
    links: "https://coinmarketcap.com/currencies/litecoin/",
  },
  {
    id: 28,
    name: "MAN",
    desc: "Matrix AI Network",
    links: "https://coinmarketcap.com/currencies/matrix-ai-network/",
  },
  {
    id: 29,
    name: "MITX",
    desc: "Morpheus Labs",
    links: "https://coinmarketcap.com/currencies/morpheus-labs/",
  },
  {
    id: 30,
    name: "MKR",
    desc: "Maker",
    links: "https://coinmarketcap.com/currencies/maker/",
  },
  {
    id: 31,
    name: "MTH",
    desc: "Monetha",
    links: "https://coinmarketcap.com/currencies/monetha/",
  },
  {
    id: 32,
    name: "MUXE",
    desc: "Muxe",
    links: "https://www.muxe.io/",
  },
  {
    id: 33,
    name: "OCN",
    desc: "Odyssey",
    links: "https://coinmarketcap.com/currencies/odyssey/",
  },
  {
    id: 34,
    name: "ORBS",
    desc: "Orbs",
    links: "https://coinmarketcap.com/currencies/orbs/",
  },
  {
    id: 35,
    name: "PMNT",
    desc: "Paymon",
    links: "https://coinmarketcap.com/currencies/paymon/",
  },
  {
    id: 36,
    name: "PPC",
    desc: "Peercoin",
    links: "https://coinmarketcap.com/currencies/peercoin/",
  },
  {
    id: 37,
    name: "QSP",
    desc: "Quantstamp",
    links: "https://coinmarketcap.com/currencies/quantstamp/",
  },
  {
    id: 38,
    name: "SHIB INU",
    desc: "Shiba Inu",
    links: "https://coinmarketcap.com/currencies/shiba-inu/",
  },
  {
    id: 39,
    name: "SNTR",
    desc: "Sentre Protocol",
    links: "https://crypto.com/price/sentre-protocol",
  },
  {
    id: 40,
    name: "SOL",
    desc: "Solana",
    links: "https://coinmarketcap.com/currencies/solana/",
  },
  {
    id: 41,
    name: "SRN",
    desc: "SIRIN LABS Token",
    links: "https://coinmarketcap.com/currencies/sirin-labs-token/",
  },
  {
    id: 42,
    name: "STQ",
    desc: "Storiqa",
    links: "https://crypto.com/price/storiqa",
  },
  {
    id: 43,
    name: "STRONG",
    desc: "Strong",
    links: "https://coinmarketcap.com/currencies/strong/",
  },
  {
    id: 44,
    name: "TRON",
    desc: "Tron",
    links: "https://coinmarketcap.com/currencies/tron/",
  },
  {
    id: 45,
    name: "USDT",
    desc: "Tether",
    links: "https://coinmarketcap.com/currencies/tether/",
  },
  {
    id: 46,
    name: "VET",
    desc: "VeChain",
    links: "https://coinmarketcap.com/currencies/vechain/",
  },
  {
    id: 47,
    name: "VOISE",
    desc: "Voise",
    links: "https://coinmarketcap.com/currencies/voisecom/",
  },
  {
    id: 48,
    name: "WPR",
    desc: "WePower",
    links: "https://coinmarketcap.com/currencies/wepower/",
  },
  {
    id: 49,
    name: "XDATA",
    desc: "Streama Xdata",
    links: "https://www.coingecko.com/en/coins/streamr-xdata",
  },
  {
    id: 50,
    name: "XLM",
    desc: "Stellar",
    links: "https://coinmarketcap.com/currencies/stellar/",
  },
  {
    id: 51,
    name: "XRP",
    desc: "XRP",
    links: "https://coinmarketcap.com/currencies/xrp/",
  },
  {
    id: 52,
    name: "YFI",
    desc: "yearn.finance",
    links: "https://coinmarketcap.com/currencies/yearn-finance/",
  },
  {
    id: 53,
    name: "ZRX",
    desc: "0x",
    links: "https://coinmarketcap.com/currencies/0x/",
  },
  {
    id: 54,
    name: "Dogecoin",
    desc: "Buff Doge Coin",
    links: null,
  },
  {
    id: 55,
    name: "SRN",
    desc: "SIRIN LABS Token",
    links: null,
  },
  {
    id: 56,
    name: "ZRX",
    desc: "0x",
    links: null,
  },
  {
    id: 57,
    name: "PPC",
    desc: "Peercoin",
    links: null,
  },
];
