export const SET_DARK_THEME = "SET_DARK_THEME";
export const SET_LIGHT_THEME = "SET_LIGHT_THEME";
export const SET_DRAWER_OPEN = "SET_DRAWER_OPEN";
export const SET_DRAWER_CLOSE = "SET_DRAWER_CLOSE";
export const SET_SECOND_DRAWER_OPEN = "SET_SECOND_DRAWER_OPEN";
export const SET_SECOND_DRAWER_CLOSE = "SET_SECOND_DRAWER_CLOSE ";
export const SET_QR_OPEN = "SET_QR_OPEN";
export const SET_QR_CLOSED = "SET_QR_CLOSED";
export const SET_ROLE_FILTER = "SET_ROLE_FILTER";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const AUTHENTICATE = "AUTHENTICATE";
export const GET_QR = "GET_QR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_PREF = "GET_USER_PREF";
export const USER_PREF = "USER_PREF";
export const SET_USER_PREF = "SET_USER_PREF";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const MODIFY_USER = "MODIFY_USER";
export const REGISTER_USER = "REGISTER_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const LOGOUT = "LOGOUT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
export const PERMISSIONS_LOADING = "PERMISSIONS_LOADING";
export const ASSETS_LOADING = "ASSETS_LOADING";

export const OPERATION_LOADING = "OPERATION_LOADING";
export const GET_USER_OPERATIONS = "GET_USER_OPERATIONS";
export const NEW_OP = "NEW_OP";
export const SELECT_OP = "SELECT_OP";
export const NEW_PORTFOLIO = "NEW_PORTFOLIO";
export const GET_PORT_BY_OP = "GET_PORT_BY_OP";
export const GET_PORT = "GET_PORT";
export const CLEAR_PORTFOLIOS = "CLEAR_PORTFOLIOS";
export const ADD_ASSET = "ADD_ASSET";
export const GET_ASSET = "GET_ASSET";
export const GET_ORG_USERS = "GET_ORG_USERS";
export const NEW_USER = "NEW_USER";
export const UPDATE_USERS = "UPDATE_USERS";
export const GET_USER_ORG = "GET_USER_ORG";
export const SELECT_ORG = "SELECT_ORG";
export const CREATE_CLIENT = "CREATE_CLIENT";

export const ORGS_LOADING = "ORGS_LOADING";
export const NEW_ADMIN_USER = "NEW_ADMIN_USER";
export const GET_ALL_ORGS = "GET_ALL_ORGS";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const ACTIVITY_LOADING = "ACTIVITY_LOADING";

export const ASSET_LOADING = "ASSET_LOADING";
export const CREATE_ASSET = "CREATE_ASSET";

export const GET_PRICING = "GET_PRICING";
export const SET_FILTER_DATA = "SET_FILTER_DATA";
export const SET_CALENDER_DATA = "SET_CALENDER_DATA";

export const GROUP_LOADING = "GROUP_LOADING";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_GROUPS = "GET_GROUPS";
export const GET_CUSTODIANS = "GET_CUSTODIANS";

export const ADD_TO_GROUP = "ADD_TO_GROUP";
export const REMOVE_FROM_GROUP = "REMOVE_FROM_GROUP";
export const SET_PORT = "SET_PORT";

export const SET_CLIENT_DATA = "SET_CLIENT_DATA";
